image: registry.gitlab.com/satoshilabs/trezor/trezor-suite/base:latest

variables:
    PACKAGE_PATH_COMPONENTS: 'packages/components-storybook'
    PACKAGE_PATH_SUITE_WEB: 'packages/suite-web'
    PACKAGE_PATH_SUITE_NATIVE: 'packages/suite-native'
    PACKAGE_PATH_SUITE_DESKTOP: 'packages/suite-desktop'
    PACKAGE_PATH_CONNECT_EXPLORER: 'packages/connect-explorer'
    DEV_SERVER_URL: 'https://suite.corp.sldev.cz'

stages:
    - install and build libraries
    - lint and prettier
    - typescript type check
    - unit testing
    - build
    - deploy to dev servers
    - integration testing

install and build:
    stage: install and build libraries
    script:
        - yarn install
        - npx lerna run build:lib
    artifacts:
        expire_in: 2 hours
        when: always
        paths:
            # libs
            - packages/components/lib
            - packages/blockchain-link/lib
            - packages/rollout/lib
            - packages/suite-storage/lib
            # node_modules
            - node_modules
            - packages/blockchain-link/node_modules
            - packages/components/node_modules
            - packages/components-storybook/node_modules
            - packages/connect-explorer/node_modules
            - packages/rollout/node_modules
            - packages/suite/node_modules
            - packages/suite-web/node_modules
            - packages/suite-desktop/node_modules
            - packages/suite-native/node_modules
            - packages/suite-storage/node_modules

.components: 
    only:
        changes: 
            -packages/components

.components-storybook: 
    only:
        changes: 
            -packages/components-storybook

.suite: 
    only:
        changes: 
            -packages/suite

.suite-web: 
    only:
        changes: 
            -packages/suite-web

.suite-desktop: 
    only:
        changes: 
            -packages/suite-desktop

.suite-native: 
    only:
        changes: 
            -packages/suite-native

.blockchain-link: 
    only:
        changes: 
            -packages/blockchain0link

.rollout: 
    only:
        changes: 
            -packages/rollout
            
.connect-explorer: 
    only:
        changes: 
            -packages/connect-explorer
            
include:
    - ci/packages/components.yml
    - ci/packages/components-storybook.yml
    - ci/packages/suite.yml
    - ci/packages/suite-web.yml
    - ci/packages/suite-desktop.yml
    - ci/packages/suite-native.yml
    - ci/packages/blockchain-link.yml
    - ci/packages/rollout.yml
    - ci/packages/connect-explorer.yml
